// actors por puesto de película y foto por persona
// Generado por tools/fetch-people.py --role actors
// Nombres: top_peliculas_taquilla_y_critica.xlsx · Fotos: Wikipedia en inglés
const ACTORS = {
  1: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver", "Stephen Lang", "Michelle Rodriguez"],
  2: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Scarlett Johansson", "Chris Hemsworth"],
  3: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver", "Kate Winslet", "Stephen Lang"],
  4: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates", "Frances Fisher"],
  5: ["Daisy Ridley", "John Boyega", "Adam Driver", "Harrison Ford", "Oscar Isaac"],
  6: ["Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo", "Chris Evans", "Scarlett Johansson"],
  7: ["Tom Holland", "Zendaya", "Jacob Batalon", "Marisa Tomei", "Jon Favreau"],
  8: ["Lü Yanting", "Han Mo", "Chen Hao", "Lü Qi", "Liu Tongzi"],
  9: ["Tom Holland", "Zendaya", "Benedict Cumberbatch", "Tobey Maguire", "Andrew Garfield"],
  10: ["Ginnifer Goodwin", "Jason Bateman", "Ke Huy Quan", "Fortune Feimster", "Idris Elba"],
  11: ["Amy Poehler", "Maya Hawke", "Ayo Edebiri", "Lewis Black", "Phyllis Smith"],
  12: ["Chris Pratt", "Bryce Dallas Howard", "Irrfan Khan", "Vincent D'Onofrio", "Nick Robinson"],
  13: ["Donald Glover", "Beyoncé", "James Earl Jones", "Seth Rogen", "Chiwetel Ejiofor"],
  14: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson", "Mark Ruffalo", "Chris Hemsworth"],
  15: ["Vin Diesel", "Paul Walker", "Dwayne Johnson", "Jason Statham", "Michelle Rodriguez"],
  16: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver", "Kate Winslet", "Oona Chaplin"],
  17: ["Tom Cruise", "Miles Teller", "Jennifer Connelly", "Jon Hamm", "Glen Powell"],
  18: ["Idina Menzel", "Kristen Bell", "Josh Gad", "Jonathan Groff", "Sterling K. Brown"],
  19: ["Margot Robbie", "Ryan Gosling", "Simu Liu", "Kate McKinnon", "America Ferrera"],
  20: ["Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Mark Ruffalo", "Scarlett Johansson"],
  21: ["Chris Pratt", "Anya Taylor-Joy", "Charlie Day", "Jack Black", "Keegan-Michael Key"],
  22: ["Matt Damon", "Tom Holland", "Zendaya", "Anne Hathaway", "Charlize Theron"],
  23: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin", "Morena Baccarin", "Matthew Macfadyen"],
  24: ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o", "Danai Gurira", "Letitia Wright"],
  25: ["Mark Hamill", "Daisy Ridley", "Adam Driver", "Carrie Fisher", "John Boyega"],
  26: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint", "Ralph Fiennes", "Alan Rickman"],
  27: ["Chris Pratt", "Bryce Dallas Howard", "Jeff Goldblum", "Rafe Spall", "James Cromwell"],
  28: ["Idina Menzel", "Kristen Bell", "Josh Gad", "Jonathan Groff", "Santino Fontana"],
  29: ["Emma Watson", "Dan Stevens", "Luke Evans", "Kevin Kline", "Josh Gad"],
  30: ["Craig T. Nelson", "Holly Hunter", "Samuel L. Jackson", "Sarah Vowell", "Huck Milner"],
  31: ["Robert Downey Jr.", "Gwyneth Paltrow", "Don Cheadle", "Guy Pearce", "Ben Kingsley"],
  32: ["Vin Diesel", "Dwayne Johnson", "Jason Statham", "Charlize Theron", "Michelle Rodriguez"],
  33: ["Sandra Bullock", "Jon Hamm", "Michael Keaton", "Steve Carell", "Pierre Coffin"],
  34: ["Chris Evans", "Robert Downey Jr.", "Scarlett Johansson", "Sebastian Stan", "Chadwick Boseman"],
  35: ["Jason Momoa", "Amber Heard", "Willem Dafoe", "Patrick Wilson", "Nicole Kidman"],
  36: ["Tom Holland", "Zendaya", "Jake Gyllenhaal", "Samuel L. Jackson", "Marisa Tomei"],
  37: ["Brie Larson", "Samuel L. Jackson", "Ben Mendelsohn", "Jude Law", "Annette Bening"],
  38: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen", "Sean Astin", "Orlando Bloom"],
  39: ["Shia LaBeouf", "Rosie Huntington-Whiteley", "Josh Duhamel", "John Turturro", "Tyrese Gibson"],
  40: ["Tom Hanks", "Tim Allen", "Annie Potts", "Keegan-Michael Key", "Joan Cusack"],
  41: ["Daniel Craig", "Javier Bardem", "Judi Dench", "Ralph Fiennes", "Naomie Harris"],
  42: ["Mark Wahlberg", "Stanley Tucci", "Kelsey Grammer", "Nicola Peltz", "Jack Reynor"],
  43: ["Christian Bale", "Tom Hardy", "Anne Hathaway", "Joseph Gordon-Levitt", "Gary Oldman"],
  44: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz", "Frances Conroy", "Brett Cullen"],
  45: ["Tom Hanks", "Tim Allen", "Annie Potts", "Tony Hale", "Keegan-Michael Key"],
  46: ["Daisy Ridley", "Adam Driver", "John Boyega", "Oscar Isaac", "Mark Hamill"],
  47: ["Tom Hanks", "Tim Allen", "Joan Cusack", "Ned Beatty", "Michael Keaton"],
  48: ["Johnny Depp", "Orlando Bloom", "Keira Knightley", "Bill Nighy", "Stellan Skarsgård"],
  49: ["Auli'i Cravalho", "Dwayne Johnson", "Hualālai Chung", "Rose Matafeo", "David Fane"],
  50: ["Sam Neill", "Laura Dern", "Jeff Goldblum", "Richard Attenborough", "Samuel L. Jackson"],
  51: ["Felicity Jones", "Diego Luna", "Donnie Yen", "Mads Mikkelsen", "Ben Mendelsohn"],
  52: ["Liam Neeson", "Ewan McGregor", "Natalie Portman", "Jake Lloyd", "Ian McDiarmid"],
  53: ["Johnny Depp", "Penélope Cruz", "Ian McShane", "Geoffrey Rush", "Kevin McNally"],
  54: ["Will Smith", "Mena Massoud", "Naomi Scott", "Marwan Kenzari", "Navid Negahban"],
  55: ["Maia Kealoha", "Chris Sanders", "Sydney Agudong", "Zach Galifianakis", "Billy Magnussen"],
  56: ["Steve Carell", "Kristen Wiig", "Trey Parker", "Steve Coogan", "Miranda Cosgrove"],
  57: ["Mia Wasikowska", "Johnny Depp", "Helena Bonham Carter", "Anne Hathaway", "Crispin Glover"],
  58: ["Ellen DeGeneres", "Albert Brooks", "Ed O'Neill", "Kaitlin Olson", "Ty Burrell"],
  60: ["Ginnifer Goodwin", "Jason Bateman", "Idris Elba", "Jenny Slate", "Nate Torrence"],
  61: ["Martin Freeman", "Ian McKellen", "Richard Armitage", "Andy Serkis", "Hugo Weaving"],
  63: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine", "Gary Oldman"],
  64: ["Chris Pratt", "Bryce Dallas Howard", "Sam Neill", "Laura Dern", "Jeff Goldblum"],
  65: ["Matthew Broderick", "James Earl Jones", "Jeremy Irons", "Nathan Lane", "Ernie Sabella"],
  66: ["Steve Carell", "Kristen Wiig", "Will Ferrell", "Pierre Coffin", "Joey King"],
  67: ["Cillian Murphy", "Emily Blunt", "Robert Downey Jr.", "Matt Damon", "Florence Pugh"],
  68: ["Steve Carell", "Kristen Wiig", "Benjamin Bratt", "Miranda Cosgrove", "Russell Brand"],
  69: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint", "Alan Rickman", "Maggie Smith"],
  70: ["Dwayne Johnson", "Jack Black", "Kevin Hart", "Karen Gillan", "Nick Jonas"],
  71: ["Jason Momoa", "Jack Black", "Danielle Brooks", "Sebastian Hansen", "Jennifer Coolidge"],
  72: ["Johnny Depp", "Orlando Bloom", "Keira Knightley", "Geoffrey Rush", "Bill Nighy"],
  73: ["Martin Freeman", "Ian McKellen", "Richard Armitage", "Benedict Cumberbatch", "Orlando Bloom"],
  74: ["Benedict Cumberbatch", "Elizabeth Olsen", "Xochitl Gomez", "Rachel McAdams", "Chiwetel Ejiofor"],
  75: ["Neel Sethi", "Bill Murray", "Ben Kingsley", "Idris Elba", "Scarlett Johansson"],
  76: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint", "Ralph Fiennes", "Alan Rickman"],
  77: ["Martin Freeman", "Ian McKellen", "Richard Armitage", "Luke Evans", "Benedict Cumberbatch"],
  78: ["Steve Carell", "Pierre Coffin", "Taraji P. Henson", "Michelle Yeoh", "Jean-Claude Van Damme"],
  79: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint", "Gary Oldman", "Ralph Fiennes"],
  80: ["Albert Brooks", "Ellen DeGeneres", "Alexander Gould", "Willem Dafoe", "Geoffrey Rush"],
  81: ["Mike Myers", "Eddie Murphy", "Cameron Diaz", "Antonio Banderas", "Julie Andrews"],
  82: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen", "Orlando Bloom", "Sean Astin"],
  83: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint", "Michael Gambon", "Alan Rickman"],
  84: ["Ewan McGregor", "Natalie Portman", "Hayden Christensen", "Ian McDiarmid", "Samuel L. Jackson"],
  85: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Sean Astin", "Orlando Bloom"],
  86: ["Tobey Maguire", "Kirsten Dunst", "James Franco", "Thomas Haden Church", "Topher Grace"],
  87: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint", "Ralph Fiennes", "Robert Pattinson"],
  88: ["Ray Romano", "John Leguizamo", "Denis Leary", "Queen Latifah", "Simon Pegg"],
  89: ["Louis C.K.", "Eric Stonestreet", "Kevin Hart", "Jenny Slate", "Ellie Kemper"],
  90: ["Ray Romano", "John Leguizamo", "Denis Leary", "Queen Latifah", "Jennifer Lopez"],
  91: ["Rami Malek", "Lucy Boynton", "Gwilym Lee", "Ben Hardy", "Joseph Mazzello"],
  92: ["Daniel Craig", "Christoph Waltz", "Léa Seydoux", "Ralph Fiennes", "Monica Bellucci"],
  93: ["Tom Holland", "Michael Keaton", "Robert Downey Jr.", "Zendaya", "Marisa Tomei"],
  94: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint", "Kenneth Branagh", "Alan Rickman"],
  95: ["Ben Affleck", "Henry Cavill", "Amy Adams", "Jesse Eisenberg", "Gal Gadot"],
  96: ["Scarlett Johansson", "Jonathan Bailey", "Mahershala Ali", "Rupert Friend", "Manuel Garcia-Rulfo"],
  97: ["Chris Pratt", "Zoe Saldana", "Dave Bautista", "Kurt Russell", "Bradley Cooper"],
  98: ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth", "Philip Seymour Hoffman", "Woody Harrelson"],
  99: ["Letitia Wright", "Lupita Nyong'o", "Danai Gurira", "Angela Bassett", "Tenoch Huerta"],
  100: ["Tom Hardy", "Michelle Williams", "Riz Ahmed", "Woody Harrelson", "Jenny Slate"],
  101: ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall", "Diane Keaton"],
  102: ["Al Pacino", "Robert De Niro", "Diane Keaton", "Robert Duvall", "John Cazale"],
  103: ["Henry Fonda", "Lee J. Cobb", "Jack Warden", "Martin Balsam", "Ed Begley"],
  104: ["Liam Neeson", "Ben Kingsley", "Ralph Fiennes", "Caroline Goodall", "Embeth Davidtz"],
  105: ["John Travolta", "Samuel L. Jackson", "Uma Thurman", "Bruce Willis", "Tim Roth"],
  106: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler", "Clancy Brown"],
  107: ["Fred MacMurray", "Barbara Stanwyck", "Edward G. Robinson", "Porter Hall", "Jean Heather"],
  108: ["Fred MacMurray", "Barbara Stanwyck", "Edward G. Robinson", "Porter Hall", "Jean Heather"],
  109: ["Charles Chaplin", "Paulette Goddard", "Henry Bergman", "Tiny Sandford", "Chester Conklin"],
  111: ["Roberto Benigni", "Nicoletta Braschi", "Giorgio Cantarini", "Giustino Durano", "Horst Buchholz"],
  112: ["Robert Redford", "Paul Newman", "Robert Shaw", "Charles Durning", "Ray Walston"],
  113: ["Fred MacMurray", "Barbara Stanwyck", "Edward G. Robinson", "Porter Hall", "Jean Heather"],
  115: ["Anthony Perkins", "Janet Leigh", "John Gavin", "Vera Miles", "Martin Balsam"],
  116: ["Ray Liotta", "Robert De Niro", "Joe Pesci", "Lorraine Bracco", "Paul Sorvino"],
  117: ["Alexandre Rodrigues", "Leandro Firmino", "Phellipe Haagensen", "Douglas Silva", "Jonathan Haagensen"],
  118: ["Clint Eastwood", "Lee Van Cleef", "Eli Wallach", "Aldo Giuffrè", "Luigi Pistilli"],
  119: ["Humphrey Bogart", "Ingrid Bergman", "Paul Henreid", "Claude Rains", "Conrad Veidt"],
  120: ["Toshirô Mifune", "Takashi Shimura", "Yoshio Inaba", "Seiji Miyaguchi", "Isao Kimura"],
  123: ["James Stewart", "Grace Kelly", "Wendell Corey", "Thelma Ritter", "Raymond Burr"],
  124: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field", "Mykelti Williamson"],
  125: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Billy Dee Williams", "Alec Guinness"],
  126: ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki", "Takashi Naitô", "Yasuko Sawaguchi"],
  127: ["Philippe Noiret", "Salvatore Cascio", "Marco Leonardi", "Jacques Perrin", "Agnese Nano"],
  128: ["Gene Kelly", "Donald O'Connor", "Debbie Reynolds", "Jean Hagen", "Millard Mitchell"],
  129: ["Fred MacMurray", "Barbara Stanwyck", "Edward G. Robinson", "Porter Hall", "Jean Heather"],
  130: ["James Stewart", "Kim Novak", "Barbara Bel Geddes", "Tom Helmore", "Henry Jones"],
  131: ["Orson Welles", "Joseph Cotten", "Everett Sloane", "Dorothy Comingore", "Agnes Moorehead"],
  133: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn", "Ted Levine", "Anthony Heald"],
  134: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik", "Park So-dam"],
  135: ["Keir Dullea", "Gary Lockwood", "William Sylvester", "Daniel Richter", "Leonard Rossiter"],
  136: ["Adrien Brody", "Thomas Kretschmann", "Frank Finlay", "Emilia Fox", "Maureen Lipman"],
  137: ["Jack Nicholson", "Louise Fletcher", "Danny DeVito", "Brad Dourif", "Christopher Lloyd"],
  138: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter", "Meat Loaf", "Jared Leto"],
  139: ["Tom Hulce", "F. Murray Abraham", "Elizabeth Berridge", "Jeffrey Jones", "Roy Dotrice"],
  140: ["Peter O'Toole", "Alec Guinness", "Anthony Quinn", "Omar Sharif", "José Ferrer"],
  141: ["Marilyn Monroe", "Tony Curtis", "Jack Lemmon", "Joe E. Brown", "George Raft"],
  142: ["Clint Eastwood", "Lee Van Cleef", "Eli Wallach", "Aldo Giuffrè", "Luigi Pistilli"],
  143: ["Robert De Niro", "Cathy Moriarty", "Joe Pesci", "Nicholas Colasanto", "Frank Vincent"],
  144: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy", "Ken Watanabe"],
  145: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Alec Guinness", "Peter Cushing"],
  146: ["Arnold Schwarzenegger", "Linda Hamilton", "Robert Patrick", "Edward Furlong", "Joe Morton"],
  147: ["Tom Hanks", "Matt Damon", "Tom Sizemore", "Edward Burns", "Barry Pepper"],
  148: ["Tom Hanks", "Michael Clarke Duncan", "David Morse", "Sam Rockwell", "James Cromwell"],
  149: ["Martin Sheen", "Marlon Brando", "Robert Duvall", "Dennis Hopper", "Laurence Fishburne"],
  150: ["Miles Teller", "J.K. Simmons", "Paul Reiser", "Melissa Benoist", "Austin Stowell"],
  151: ["Kevin Spacey", "Gabriel Byrne", "Benicio del Toro", "Chazz Palminteri", "Stephen Baldwin"],
  152: ["William Holden", "Alec Guinness", "Jack Hawkins", "Sessue Hayakawa", "James Donald"],
  153: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving", "Joe Pantoliano"],
  154: ["Clark Gable", "Vivien Leigh", "Olivia de Havilland", "Leslie Howard", "Hattie McDaniel"],
  155: ["Harrison Ford", "Karen Allen", "Paul Freeman", "John Rhys-Davies", "Ronald Lacey"],
  156: ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson", "Crispin Glover", "Thomas F. Wilson"],
  157: ["Jim Carrey", "Ed Harris", "Laura Linney", "Noah Emmerich", "Natascha McElhone"],
  158: ["Sigourney Weaver", "Tom Skerritt", "John Hurt", "Ian Holm", "Yaphet Kotto"],
  159: ["Hugh Jackman", "Christian Bale", "Scarlett Johansson", "Michael Caine", "David Bowie"],
  160: ["Charlton Heston", "Jack Hawkins", "Stephen Boyd", "Hugh Griffith", "Martha Scott"],
  161: ["Jim Carrey", "Kate Winslet", "Kirsten Dunst", "Mark Ruffalo", "Elijah Wood"],
  162: ["Robert De Niro", "Jodie Foster", "Cybill Shepherd", "Harvey Keitel", "Peter Boyle"],
  163: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine", "Matt Damon"],
  164: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen", "Oliver Reed", "Richard Harris"],
  165: ["Kevin Spacey", "Annette Bening", "Thora Birch", "Wes Bentley", "Mena Suvari"],
  166: ["Audrey Tautou", "Mathieu Kassovitz", "Rufus", "Jamel Debbouze", "Dominique Pinon"],
  167: ["Michelle Yeoh", "Ke Huy Quan", "Stephanie Hsu", "Jamie Lee Curtis", "James Hong"],
  168: ["Jean Reno", "Natalie Portman", "Gary Oldman", "Danny Aiello", "Peter Appel"],
  169: ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd", "Scatman Crothers", "Barry Nelson"],
  170: ["Harrison Ford", "Rutger Hauer", "Sean Young", "Daryl Hannah", "Edward James Olmos"],
  171: ["Malcolm McDowell", "Patrick Magee", "Michael Bates", "Warren Clarke", "Adrienne Corri"],
  172: ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson", "Mark Wahlberg", "Martin Sheen"],
  173: ["Javier Bardem", "Josh Brolin", "Tommy Lee Jones", "Woody Harrelson", "Kelly Macdonald"],
  174: ["Al Pacino", "Steven Bauer", "Michelle Pfeiffer", "Mary Elizabeth Mastrantonio", "Robert Loggia"],
  175: ["Henry Thomas", "Drew Barrymore", "Dee Wallace", "Robert MacNaughton", "Peter Coyote"],
  176: ["Roy Scheider", "Robert Shaw", "Richard Dreyfuss", "Lorraine Gary", "Murray Hamilton"],
  177: ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio", "Kerry Washington", "Samuel L. Jackson"],
  178: ["Brad Pitt", "Christoph Waltz", "Mélanie Laurent", "Michael Fassbender", "Eli Roth"],
  179: ["Mel Gibson", "Sophie Marceau", "Patrick McGoohan", "Catherine McCormack", "Angus Macfadyen"],
  180: ["Chiwetel Ejiofor", "Michael Fassbender", "Lupita Nyong'o", "Brad Pitt", "Benedict Cumberbatch"],
  181: ["Ralph Fiennes", "Tony Revolori", "Saoirse Ronan", "Adrien Brody", "Willem Dafoe"],
  182: ["Daniel Day-Lewis", "Paul Dano", "Kevin J. O'Connor", "Ciarán Hinds", "Dillon Freasier"],
  183: ["Matthew Modine", "R. Lee Ermey", "Vincent D'Onofrio", "Adam Baldwin", "Arliss Howard"],
  184: ["Jesse Eisenberg", "Andrew Garfield", "Justin Timberlake", "Armie Hammer", "Rooney Mara"],
  185: ["Mahershala Ali", "Naomie Harris", "Trevante Rhodes", "André Holland", "Janelle Monáe"],
  186: ["Ryan Gosling", "Emma Stone", "John Legend", "J.K. Simmons", "Rosemarie DeWitt"],
  187: ["Frances McDormand", "David Strathairn", "Linda May", "Swankie", "Bob Wells"],
  188: ["Al Pacino", "Diane Keaton", "Andy García", "Talia Shire", "Eli Wallach"],
  189: ["Sandra Bullock", "George Clooney", "Ed Harris", "Paul Sharma", "Basher Savage"],
  190: ["Sally Hawkins", "Michael Shannon", "Richard Jenkins", "Octavia Spencer", "Doug Jones"],
  191: ["Leonardo DiCaprio", "Tom Hardy", "Domhnall Gleeson", "Will Poulter", "Forrest Goodluck"],
  192: ["Brad Pitt", "Morgan Freeman", "Kevin Spacey", "Gwyneth Paltrow", "R. Lee Ermey"],
  193: ["Jack Nicholson", "Faye Dunaway", "John Huston", "Perry Lopez", "John Hillerman"],
  194: ["James Stewart", "Donna Reed", "Lionel Barrymore", "Henry Travers", "Thomas Mitchell"],
  197: ["Fred MacMurray", "Barbara Stanwyck", "Edward G. Robinson", "Porter Hall", "Jean Heather"],
  198: ["Cary Grant", "Eva Marie Saint", "James Mason", "Leo G. Carroll", "Jessie Royce Landis"],
  199: ["Woody Allen", "Diane Keaton", "Tony Roberts", "Carol Kane", "Paul Simon"],
  200: ["Robert De Niro", "Christopher Walken", "Meryl Streep", "John Savage", "John Cazale"],
  201: ["Faye Dunaway", "William Holden", "Peter Finch", "Robert Duvall", "Beatrice Straight"],
  202: ["Clint Eastwood", "Gene Hackman", "Morgan Freeman", "Richard Harris", "Jaimz Woolvett"],
  203: ["Charlie Sheen", "Tom Berenger", "Willem Dafoe", "Keith David", "Forest Whitaker"],
  204: ["Ivana Baquero", "Sergi López", "Doug Jones", "Maribel Verdú", "Ariadna Gil"],
  205: ["Ulrich Mühe", "Martina Gedeck", "Sebastian Koch", "Ulrich Tukur", "Thomas Thieme"],
  206: ["Tony Leung", "Maggie Cheung", "Ping Lam Siu", "Rebecca Pan", "Lai Chin"],
  209: ["Guy Pearce", "Carrie-Anne Moss", "Joe Pantoliano", "Mark Boone Junior", "Stephen Tobolowsky"],
  210: ["Choi Min-sik", "Yoo Ji-tae", "Kang Hye-jung", "Kim Byung-ok", "Oh Dal-su"],
  211: ["Harvey Keitel", "Tim Roth", "Steve Buscemi", "Michael Madsen", "Chris Penn"],
  212: ["Michael Keaton", "Mark Ruffalo", "Rachel McAdams", "Liev Schreiber", "Stanley Tucci"],
  213: ["Michael Keaton", "Edward Norton", "Emma Stone", "Zach Galifianakis", "Naomi Watts"],
  214: ["Colin Firth", "Geoffrey Rush", "Helena Bonham Carter", "Guy Pearce", "Derek Jacobi"],
  215: ["Ben Affleck", "Bryan Cranston", "Alan Arkin", "John Goodman", "Clea DuVall"],
  216: ["Dev Patel", "Freida Pinto", "Anil Kapoor", "Irrfan Khan", "Saurabh Shukla"],
  217: ["Emilia Jones", "Troy Kotsur", "Marlee Matlin", "Daniel Durant", "Eugenio Derbez"],
  218: ["Viggo Mortensen", "Mahershala Ali", "Linda Cardellini", "Sebastian Maniscalco", "Dimiter Marinov"],
  219: ["George MacKay", "Dean-Charles Chapman", "Mark Strong", "Colin Firth", "Benedict Cumberbatch"],
  220: ["Anthony Gonzalez", "Gael García Bernal", "Benjamin Bratt", "Alanna Ubach", "Renée Victor"],
  221: ["Gal Gadot", "Chris Pine", "Robin Wright", "Danny Huston", "David Thewlis"],
  222: ["Tobey Maguire", "Kirsten Dunst", "Willem Dafoe", "James Franco", "Cliff Robertson"],
  223: ["Will Smith", "Jeff Goldblum", "Bill Pullman", "Mary McDonnell", "Judd Hirsch"],
  224: ["Chris Pratt", "Zoe Saldana", "Dave Bautista", "Vin Diesel", "Bradley Cooper"],
  225: ["Chris Hemsworth", "Tom Hiddleston", "Cate Blanchett", "Jeff Goldblum", "Tessa Thompson"],
  226: ["Ed Asner", "Jordan Nagai", "Christopher Plummer", "Bob Peterson", "Delroy Lindo"],
  227: ["Craig T. Nelson", "Holly Hunter", "Samuel L. Jackson", "Jason Lee", "Spencer Fox"],
  228: ["Timothée Chalamet", "Zendaya", "Austin Butler", "Florence Pugh", "Javier Bardem"],
  229: ["Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac", "Zendaya", "Jason Momoa"],
  230: ["Hugh Jackman", "Patrick Stewart", "Dafne Keen", "Boyd Holbrook", "Stephen Merchant"],
  231: ["Ben Burtt", "Elissa Knight", "Jeff Garlin", "Fred Willard", "Sigourney Weaver"],
  232: ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie", "Matthew McConaughey", "Kyle Chandler"],
  233: ["Joaquin Phoenix", "Scarlett Johansson", "Amy Adams", "Rooney Mara", "Chris Pratt"],
  234: ["Amy Adams", "Jeremy Renner", "Forest Whitaker", "Michael Stuhlbarg", "Mark O'Brien"],
  235: ["Fionn Whitehead", "Tom Hardy", "Mark Rylance", "Kenneth Branagh", "Cillian Murphy"],
};

const ACTOR_PHOTOS = {
  "Aaron Eckhart": "aaron-eckhart.jpg",
  "Adam Baldwin": "adam-baldwin.jpg",
  "Adam Driver": "adam-driver.jpg",
  "Adolphe Menjou": "adolphe-menjou.jpg",
  "Adrien Brody": "adrien-brody.jpg",
  "Adrienne Corri": "adrienne-corri.jpg",
  "Agnes Moorehead": "agnes-moorehead.jpg",
  "Al Ernest Garcia": "al-ernest-garcia.jpg",
  "Al Pacino": "al-pacino.jpg",
  "Alan Arkin": "alan-arkin.jpg",
  "Alan Rickman": "alan-rickman.jpg",
  "Alanna Ubach": "alanna-ubach.jpg",
  "Albert Brooks": "albert-brooks.jpg",
  "Aldo Giuffrè": "aldo-giuffre.jpg",
  "Alec Guinness": "alec-guinness.jpg",
  "Alexander Gould": "alexander-gould.jpg",
  "Alida Valli": "alida-valli.jpg",
  "Amber Heard": "amber-heard.jpg",
  "America Ferrera": "america-ferrera.jpg",
  "Amy Adams": "amy-adams.jpg",
  "Amy Poehler": "amy-poehler.jpg",
  "Andrew Garfield": "andrew-garfield.jpg",
  "André Holland": "andre-holland.jpg",
  "Andy García": "andy-garcia.jpg",
  "Andy Serkis": "andy-serkis.jpg",
  "Angela Bassett": "angela-bassett.jpg",
  "Angus Macfadyen": "angus-macfadyen.jpg",
  "Anil Kapoor": "anil-kapoor.jpg",
  "Anne Baxter": "anne-baxter.jpg",
  "Anne Hathaway": "anne-hathaway.jpg",
  "Annette Bening": "annette-bening.jpg",
  "Annie Potts": "annie-potts.jpg",
  "Anouk Aimée": "anouk-aimee.jpg",
  "Anthony Gonzalez": "anthony-gonzalez.jpg",
  "Anthony Hopkins": "anthony-hopkins.jpg",
  "Anthony Perkins": "anthony-perkins.jpg",
  "Anthony Quinn": "anthony-quinn.jpg",
  "Antonio Banderas": "antonio-banderas.jpg",
  "Anya Taylor-Joy": "anya-taylor-joy.jpg",
  "Ariadna Gil": "ariadna-gil.jpg",
  "Armie Hammer": "armie-hammer.jpg",
  "Arnold Schwarzenegger": "arnold-schwarzenegger.jpg",
  "Audrey Tautou": "audrey-tautou.jpg",
  "Auli'i Cravalho": "auli-i-cravalho.jpg",
  "Austin Butler": "austin-butler.jpg",
  "Austin Stowell": "austin-stowell.jpg",
  "Ayo Edebiri": "ayo-edebiri.jpg",
  "Barbara Bel Geddes": "barbara-bel-geddes.jpg",
  "Barbara Stanwyck": "barbara-stanwyck.jpg",
  "Barry Nelson": "barry-nelson.jpg",
  "Barry Pepper": "barry-pepper.jpg",
  "Beatrice Straight": "beatrice-straight.jpg",
  "Ben Affleck": "ben-affleck.jpg",
  "Ben Burtt": "ben-burtt.jpg",
  "Ben Hardy": "ben-hardy.jpg",
  "Ben Kingsley": "ben-kingsley.jpg",
  "Ben Mendelsohn": "ben-mendelsohn.jpg",
  "Benedict Cumberbatch": "benedict-cumberbatch.jpg",
  "Benicio del Toro": "benicio-del-toro.jpg",
  "Benjamin Bratt": "benjamin-bratt.jpg",
  "Bernard Lee": "bernard-lee.jpg",
  "Bette Davis": "bette-davis.jpg",
  "Beyoncé": "beyonce.jpg",
  "Bill Murray": "bill-murray.jpg",
  "Bill Nighy": "bill-nighy.jpg",
  "Bill Pullman": "bill-pullman.jpg",
  "Billy Dee Williams": "billy-dee-williams.jpg",
  "Billy Magnussen": "billy-magnussen.jpg",
  "Billy Zane": "billy-zane.jpg",
  "Bob Gunton": "bob-gunton.jpg",
  "Boyd Holbrook": "boyd-holbrook.jpg",
  "Brad Dourif": "brad-dourif.jpg",
  "Brad Pitt": "brad-pitt.jpg",
  "Bradley Cooper": "bradley-cooper.jpg",
  "Brett Cullen": "brett-cullen.jpg",
  "Brie Larson": "brie-larson.jpg",
  "Bruce Willis": "bruce-willis.jpg",
  "Bryan Cranston": "bryan-cranston.jpg",
  "Bryce Dallas Howard": "bryce-dallas-howard.jpg",
  "Cameron Diaz": "cameron-diaz.jpg",
  "Carol Kane": "carol-kane.jpg",
  "Carole Lombard": "carole-lombard.jpg",
  "Caroline Goodall": "caroline-goodall.jpg",
  "Carrie Fisher": "carrie-fisher.jpg",
  "Carrie-Anne Moss": "carrie-anne-moss.jpg",
  "Cary Grant": "cary-grant.jpg",
  "Cate Blanchett": "cate-blanchett.jpg",
  "Catherine McCormack": "catherine-mccormack.jpg",
  "Cathy Moriarty": "cathy-moriarty.jpg",
  "Celeste Holm": "celeste-holm.jpg",
  "Chadwick Boseman": "chadwick-boseman.jpg",
  "Charles Bronson": "charles-bronson.jpg",
  "Charles Chaplin": "charles-chaplin.jpg",
  "Charles Durning": "charles-durning.jpg",
  "Charles Laughton": "charles-laughton.jpg",
  "Charlie Day": "charlie-day.jpg",
  "Charlie Sheen": "charlie-sheen.jpg",
  "Charlize Theron": "charlize-theron.jpg",
  "Charlton Heston": "charlton-heston.jpg",
  "Chazz Palminteri": "chazz-palminteri.jpg",
  "Chen Hao": "chen-hao.jpg",
  "Chester Conklin": "chester-conklin.jpg",
  "Chiwetel Ejiofor": "chiwetel-ejiofor.jpg",
  "Cho Yeo-jeong": "cho-yeo-jeong.jpg",
  "Choi Min-sik": "choi-min-sik.jpg",
  "Choi Woo-shik": "choi-woo-shik.jpg",
  "Chris Evans": "chris-evans.jpg",
  "Chris Hemsworth": "chris-hemsworth.jpg",
  "Chris Penn": "chris-penn.jpg",
  "Chris Pine": "chris-pine.jpg",
  "Chris Pratt": "chris-pratt.jpg",
  "Chris Sanders": "chris-sanders.jpg",
  "Christian Bale": "christian-bale.jpg",
  "Christoph Waltz": "christoph-waltz.jpg",
  "Christopher Lloyd": "christopher-lloyd.jpg",
  "Christopher Plummer": "christopher-plummer.jpg",
  "Christopher Walken": "christopher-walken.jpg",
  "Ciarán Hinds": "ciaran-hinds.jpg",
  "Cillian Murphy": "cillian-murphy.jpg",
  "Claire Maurier": "claire-maurier.jpg",
  "Clancy Brown": "clancy-brown.jpg",
  "Clark Gable": "clark-gable.jpg",
  "Claude Rains": "claude-rains.jpg",
  "Claudia Cardinale": "claudia-cardinale.jpg",
  "Clea DuVall": "clea-duvall.jpg",
  "Cliff Robertson": "cliff-robertson.jpg",
  "Clint Eastwood": "clint-eastwood.jpg",
  "Colin Firth": "colin-firth.jpg",
  "Connie Nielsen": "connie-nielsen.jpg",
  "Conrad Veidt": "conrad-veidt.jpg",
  "Craig T. Nelson": "craig-t-nelson.jpg",
  "Crispin Glover": "crispin-glover.jpg",
  "Cybill Shepherd": "cybill-shepherd.jpg",
  "Dafne Keen": "dafne-keen.jpg",
  "Daisy Ridley": "daisy-ridley.jpg",
  "Dan Stevens": "dan-stevens.jpg",
  "Danai Gurira": "danai-gurira.jpg",
  "Daniel Craig": "daniel-craig.jpg",
  "Daniel Day-Lewis": "daniel-day-lewis.jpg",
  "Daniel Durant": "daniel-durant.jpg",
  "Daniel Radcliffe": "daniel-radcliffe.jpg",
  "Danielle Brooks": "danielle-brooks.jpg",
  "Danny Aiello": "danny-aiello.jpg",
  "Danny DeVito": "danny-devito.jpg",
  "Danny Huston": "danny-huston.jpg",
  "Danny Lloyd": "danny-lloyd.jpg",
  "Daryl Hannah": "daryl-hannah.jpg",
  "Dave Bautista": "dave-bautista.jpg",
  "David Bowie": "david-bowie.jpg",
  "David Fane": "david-fane.jpg",
  "David Morse": "david-morse.jpg",
  "David Strathairn": "david-strathairn.jpg",
  "David Thewlis": "david-thewlis.jpg",
  "Dean-Charles Chapman": "dean-charles-chapman.jpg",
  "Debbie Reynolds": "debbie-reynolds.jpg",
  "Dee Wallace": "dee-wallace.jpg",
  "Delroy Lindo": "delroy-lindo.jpg",
  "Denis Leary": "denis-leary.jpg",
  "Dennis Hopper": "dennis-hopper.jpg",
  "Derek Jacobi": "derek-jacobi.jpg",
  "Dev Patel": "dev-patel.jpg",
  "Diane Keaton": "diane-keaton.jpg",
  "Diego Luna": "diego-luna.jpg",
  "Dimiter Marinov": "dimiter-marinov.jpg",
  "Domhnall Gleeson": "domhnall-gleeson.jpg",
  "Dominique Pinon": "dominique-pinon.jpg",
  "Don Cheadle": "don-cheadle.jpg",
  "Donald Glover": "donald-glover.jpg",
  "Donald O'Connor": "donald-o-connor.jpg",
  "Donna Reed": "donna-reed.jpg",
  "Donnie Yen": "donnie-yen.jpg",
  "Dorothy Comingore": "dorothy-comingore.jpg",
  "Doug Jones": "doug-jones.jpg",
  "Douglas Silva": "douglas-silva.jpg",
  "Drew Barrymore": "drew-barrymore.jpg",
  "Dwayne Johnson": "dwayne-johnson.jpg",
  "Ed Asner": "ed-asner.jpg",
  "Ed Begley": "ed-begley.jpg",
  "Ed Harris": "ed-harris.jpg",
  "Ed O'Neill": "ed-o-neill.jpg",
  "Eddie Murphy": "eddie-murphy.jpg",
  "Edward Burns": "edward-burns.jpg",
  "Edward Furlong": "edward-furlong.jpg",
  "Edward G. Robinson": "edward-g-robinson.jpg",
  "Edward James Olmos": "edward-james-olmos.jpg",
  "Edward Norton": "edward-norton.jpg",
  "Eli Roth": "eli-roth.jpg",
  "Eli Wallach": "eli-wallach.jpg",
  "Elijah Wood": "elijah-wood.jpg",
  "Elizabeth Olsen": "elizabeth-olsen.jpg",
  "Ellen DeGeneres": "ellen-degeneres.jpg",
  "Ellie Kemper": "ellie-kemper.jpg",
  "Elliot Page": "elliot-page.jpg",
  "Elsa Lanchester": "elsa-lanchester.jpg",
  "Embeth Davidtz": "embeth-davidtz.jpg",
  "Emilia Fox": "emilia-fox.jpg",
  "Emilia Jones": "emilia-jones.jpg",
  "Emily Blunt": "emily-blunt.jpg",
  "Emma Corrin": "emma-corrin.jpg",
  "Emma Stone": "emma-stone.jpg",
  "Emma Watson": "emma-watson.jpg",
  "Enzo Staiola": "enzo-staiola.jpg",
  "Eric Stonestreet": "eric-stonestreet.jpg",
  "Erich von Stroheim": "erich-von-stroheim.jpg",
  "Ernie Sabella": "ernie-sabella.jpg",
  "Eugenio Derbez": "eugenio-derbez.jpg",
  "Eva Marie Saint": "eva-marie-saint.jpg",
  "Everett Sloane": "everett-sloane.jpg",
  "Ewan McGregor": "ewan-mcgregor.jpg",
  "F. Murray Abraham": "f-murray-abraham.jpg",
  "Faye Dunaway": "faye-dunaway.jpg",
  "Felicity Jones": "felicity-jones.jpg",
  "Felix Bressart": "felix-bressart.jpg",
  "Fionn Whitehead": "fionn-whitehead.jpg",
  "Florence Lee": "florence-lee.jpg",
  "Florence Pugh": "florence-pugh.jpg",
  "Forest Whitaker": "forest-whitaker.jpg",
  "Fortune Feimster": "fortune-feimster.jpg",
  "Frances Conroy": "frances-conroy.jpg",
  "Frances Fisher": "frances-fisher.jpg",
  "Frances McDormand": "frances-mcdormand.jpg",
  "Frank Finlay": "frank-finlay.jpg",
  "Frank Vincent": "frank-vincent.jpg",
  "Fred Clark": "fred-clark.jpg",
  "Fred MacMurray": "fred-macmurray.jpg",
  "Fred Willard": "fred-willard.jpg",
  "Freida Pinto": "freida-pinto.jpg",
  "Gabriel Byrne": "gabriel-byrne.jpg",
  "Gabriele Ferzetti": "gabriele-ferzetti.jpg",
  "Gael García Bernal": "gael-garcia-bernal.jpg",
  "Gal Gadot": "gal-gadot.jpg",
  "Gary Lockwood": "gary-lockwood.jpg",
  "Gary Merrill": "gary-merrill.jpg",
  "Gary Oldman": "gary-oldman.jpg",
  "Gary Sinise": "gary-sinise.jpg",
  "Gene Hackman": "gene-hackman.jpg",
  "Gene Kelly": "gene-kelly.jpg",
  "Geoffrey Rush": "geoffrey-rush.jpg",
  "George Clooney": "george-clooney.jpg",
  "George MacKay": "george-mackay.jpg",
  "George Macready": "george-macready.jpg",
  "George Raft": "george-raft.jpg",
  "George Sanders": "george-sanders.jpg",
  "Ginnifer Goodwin": "ginnifer-goodwin.jpg",
  "Giorgio Cantarini": "giorgio-cantarini.jpg",
  "Giustino Durano": "giustino-durano.jpg",
  "Glen Powell": "glen-powell.jpg",
  "Gloria Swanson": "gloria-swanson.jpg",
  "Grace Kelly": "grace-kelly.jpg",
  "Guy Pearce": "guy-pearce.jpg",
  "Gwilym Lee": "gwilym-lee.jpg",
  "Gwyneth Paltrow": "gwyneth-paltrow.jpg",
  "Harrison Ford": "harrison-ford.jpg",
  "Harry Myers": "harry-myers.jpg",
  "Harvey Keitel": "harvey-keitel.jpg",
  "Hattie McDaniel": "hattie-mcdaniel.jpg",
  "Hayden Christensen": "hayden-christensen.jpg",
  "Heath Ledger": "heath-ledger.jpg",
  "Helena Bonham Carter": "helena-bonham-carter.jpg",
  "Henry Bergman": "henry-bergman.jpg",
  "Henry Cavill": "henry-cavill.jpg",
  "Henry Daniell": "henry-daniell.jpg",
  "Henry Fonda": "henry-fonda.jpg",
  "Henry Jones": "henry-jones.jpg",
  "Henry Thomas": "henry-thomas.jpg",
  "Henry Travers": "henry-travers.jpg",
  "Holly Hunter": "holly-hunter.jpg",
  "Horst Buchholz": "horst-buchholz.jpg",
  "Hugh Griffith": "hugh-griffith.jpg",
  "Hugh Jackman": "hugh-jackman.jpg",
  "Hugo Weaving": "hugo-weaving.jpg",
  "Humphrey Bogart": "humphrey-bogart.jpg",
  "Ian Holm": "ian-holm.jpg",
  "Ian McDiarmid": "ian-mcdiarmid.jpg",
  "Ian McKellen": "ian-mckellen.jpg",
  "Ian McShane": "ian-mcshane.jpg",
  "Idina Menzel": "idina-menzel.jpg",
  "Idris Elba": "idris-elba.jpg",
  "Ingrid Bergman": "ingrid-bergman.jpg",
  "Irrfan Khan": "irrfan-khan.jpg",
  "Isao Kimura": "isao-kimura.jpg",
  "Ivana Baquero": "ivana-baquero.jpg",
  "J.K. Simmons": "j-k-simmons.jpg",
  "Jack Benny": "jack-benny.jpg",
  "Jack Black": "jack-black.jpg",
  "Jack Hawkins": "jack-hawkins.jpg",
  "Jack Kruschen": "jack-kruschen.jpg",
  "Jack Lemmon": "jack-lemmon.jpg",
  "Jack Nicholson": "jack-nicholson.jpg",
  "Jack Oakie": "jack-oakie.jpg",
  "Jack Reynor": "jack-reynor.jpg",
  "Jack Warden": "jack-warden.jpg",
  "Jacob Batalon": "jacob-batalon.jpg",
  "Jacques Perrin": "jacques-perrin.jpg",
  "Jake Gyllenhaal": "jake-gyllenhaal.jpg",
  "Jake Lloyd": "jake-lloyd.jpg",
  "Jamel Debbouze": "jamel-debbouze.jpg",
  "James Caan": "james-caan.jpg",
  "James Cromwell": "james-cromwell.jpg",
  "James Donald": "james-donald.jpg",
  "James Earl Jones": "james-earl-jones.jpg",
  "James Franco": "james-franco.jpg",
  "James Hong": "james-hong.jpg",
  "James Mason": "james-mason.jpg",
  "James Stewart": "james-stewart.jpg",
  "Jamie Foxx": "jamie-foxx.jpg",
  "Jamie Lee Curtis": "jamie-lee-curtis.jpg",
  "Janelle Monáe": "janelle-monae.jpg",
  "Janet Leigh": "janet-leigh.jpg",
  "Jared Leto": "jared-leto.jpg",
  "Jason Bateman": "jason-bateman.jpg",
  "Jason Lee": "jason-lee.jpg",
  "Jason Momoa": "jason-momoa.jpg",
  "Jason Robards": "jason-robards.jpg",
  "Jason Statham": "jason-statham.jpg",
  "Javier Bardem": "javier-bardem.jpg",
  "Jean Hagen": "jean-hagen.jpg",
  "Jean Heather": "jean-heather.jpg",
  "Jean Reno": "jean-reno.jpg",
  "Jean-Claude Van Damme": "jean-claude-van-damme.jpg",
  "Jean-Pierre Léaud": "jean-pierre-leaud.jpg",
  "Jeff Garlin": "jeff-garlin.jpg",
  "Jeff Goldblum": "jeff-goldblum.jpg",
  "Jeffrey Jones": "jeffrey-jones.jpg",
  "Jennifer Connelly": "jennifer-connelly.jpg",
  "Jennifer Coolidge": "jennifer-coolidge.jpg",
  "Jennifer Lawrence": "jennifer-lawrence.jpg",
  "Jennifer Lopez": "jennifer-lopez.jpg",
  "Jenny Slate": "jenny-slate.jpg",
  "Jeremy Irons": "jeremy-irons.jpg",
  "Jeremy Renner": "jeremy-renner.jpg",
  "Jesse Eisenberg": "jesse-eisenberg.jpg",
  "Jessica Chastain": "jessica-chastain.jpg",
  "Jessie Royce Landis": "jessie-royce-landis.jpg",
  "Jim Carrey": "jim-carrey.jpg",
  "Joan Cusack": "joan-cusack.jpg",
  "Joaquin Phoenix": "joaquin-phoenix.jpg",
  "Jodie Foster": "jodie-foster.jpg",
  "Joe E. Brown": "joe-e-brown.jpg",
  "Joe Morton": "joe-morton.jpg",
  "Joe Pantoliano": "joe-pantoliano.jpg",
  "Joe Pesci": "joe-pesci.jpg",
  "Joey King": "joey-king.jpg",
  "John Boyega": "john-boyega.jpg",
  "John Cazale": "john-cazale.jpg",
  "John Gavin": "john-gavin.jpg",
  "John Goodman": "john-goodman.jpg",
  "John Hillerman": "john-hillerman.jpg",
  "John Hurt": "john-hurt.jpg",
  "John Huston": "john-huston.jpg",
  "John Legend": "john-legend.jpg",
  "John Leguizamo": "john-leguizamo.jpg",
  "John Rhys-Davies": "john-rhys-davies.jpg",
  "John Savage": "john-savage.jpg",
  "John Travolta": "john-travolta.jpg",
  "John Turturro": "john-turturro.jpg",
  "John Williams": "john-williams.jpg",
  "Johnny Depp": "johnny-depp.jpg",
  "Jon Favreau": "jon-favreau.jpg",
  "Jon Hamm": "jon-hamm.jpg",
  "Jonah Hill": "jonah-hill.jpg",
  "Jonathan Bailey": "jonathan-bailey.jpg",
  "Jonathan Groff": "jonathan-groff.jpg",
  "Joseph Cotten": "joseph-cotten.jpg",
  "Joseph Gordon-Levitt": "joseph-gordon-levitt.jpg",
  "Joseph Mazzello": "joseph-mazzello.jpg",
  "Josh Brolin": "josh-brolin.jpg",
  "Josh Duhamel": "josh-duhamel.jpg",
  "Josh Gad": "josh-gad.jpg",
  "Josh Hutcherson": "josh-hutcherson.jpg",
  "José Ferrer": "jose-ferrer.jpg",
  "Judd Hirsch": "judd-hirsch.jpg",
  "Jude Law": "jude-law.jpg",
  "Judi Dench": "judi-dench.jpg",
  "Julie Andrews": "julie-andrews.jpg",
  "Justin Timberlake": "justin-timberlake.jpg",
  "Kaitlin Olson": "kaitlin-olson.jpg",
  "Kang Hye-jung": "kang-hye-jung.jpg",
  "Karen Allen": "karen-allen.jpg",
  "Karen Gillan": "karen-gillan.jpg",
  "Kate McKinnon": "kate-mckinnon.jpg",
  "Kate Winslet": "kate-winslet.jpg",
  "Kathy Bates": "kathy-bates.jpg",
  "Ke Huy Quan": "ke-huy-quan.jpg",
  "Keanu Reeves": "keanu-reeves.jpg",
  "Keegan-Michael Key": "keegan-michael-key.jpg",
  "Keir Dullea": "keir-dullea.jpg",
  "Keira Knightley": "keira-knightley.jpg",
  "Keith David": "keith-david.jpg",
  "Kelly Macdonald": "kelly-macdonald.jpg",
  "Kelsey Grammer": "kelsey-grammer.jpg",
  "Ken Watanabe": "ken-watanabe.jpg",
  "Kenneth Branagh": "kenneth-branagh.jpg",
  "Kerry Washington": "kerry-washington.jpg",
  "Kevin Hart": "kevin-hart.jpg",
  "Kevin Kline": "kevin-kline.jpg",
  "Kevin McNally": "kevin-mcnally.jpg",
  "Kevin Spacey": "kevin-spacey.jpg",
  "Kim Byung-ok": "kim-byung-ok.jpg",
  "Kim Novak": "kim-novak.jpg",
  "Kirk Douglas": "kirk-douglas.jpg",
  "Kirsten Dunst": "kirsten-dunst.jpg",
  "Kristen Bell": "kristen-bell.jpg",
  "Kristen Wiig": "kristen-wiig.jpg",
  "Kurt Russell": "kurt-russell.jpg",
  "Kyle Chandler": "kyle-chandler.jpg",
  "Lamberto Maggiorani": "lamberto-maggiorani.jpg",
  "Laura Dern": "laura-dern.jpg",
  "Laura Linney": "laura-linney.jpg",
  "Laurence Fishburne": "laurence-fishburne.jpg",
  "Lea Thompson": "lea-thompson.jpg",
  "Lee J. Cobb": "lee-j-cobb.jpg",
  "Lee Sun-kyun": "lee-sun-kyun.jpg",
  "Lee Van Cleef": "lee-van-cleef.jpg",
  "Leo G. Carroll": "leo-g-carroll.jpg",
  "Leonard Rossiter": "leonard-rossiter.jpg",
  "Leonardo DiCaprio": "leonardo-dicaprio.jpg",
  "Leslie Howard": "leslie-howard.jpg",
  "Letitia Wright": "letitia-wright.jpg",
  "Lewis Black": "lewis-black.jpg",
  "Liam Hemsworth": "liam-hemsworth.jpg",
  "Liam Neeson": "liam-neeson.jpg",
  "Lianella Carell": "lianella-carell.jpg",
  "Liev Schreiber": "liev-schreiber.jpg",
  "Linda Cardellini": "linda-cardellini.jpg",
  "Linda Hamilton": "linda-hamilton.jpg",
  "Lionel Atwill": "lionel-atwill.jpg",
  "Lionel Barrymore": "lionel-barrymore.jpg",
  "Lorraine Bracco": "lorraine-bracco.jpg",
  "Louis C.K.": "louis-c-k.jpg",
  "Louise Fletcher": "louise-fletcher.jpg",
  "Lucy Boynton": "lucy-boynton.jpg",
  "Luigi Pistilli": "luigi-pistilli.jpg",
  "Luke Evans": "luke-evans.jpg",
  "Lupita Nyong'o": "lupita-nyong-o.jpg",
  "Léa Seydoux": "lea-seydoux.jpg",
  "Machiko Kyô": "machiko-kyo.jpg",
  "Mads Mikkelsen": "mads-mikkelsen.jpg",
  "Maggie Cheung": "maggie-cheung.jpg",
  "Maggie Smith": "maggie-smith.jpg",
  "Mahershala Ali": "mahershala-ali.jpg",
  "Malcolm McDowell": "malcolm-mcdowell.jpg",
  "Manuel Garcia-Rulfo": "manuel-garcia-rulfo.jpg",
  "Marcello Mastroianni": "marcello-mastroianni.jpg",
  "Margot Robbie": "margot-robbie.jpg",
  "Mari Natsuki": "mari-natsuki.jpg",
  "Maribel Verdú": "maribel-verdu.jpg",
  "Marilyn Monroe": "marilyn-monroe.jpg",
  "Marisa Tomei": "marisa-tomei.jpg",
  "Mark Boone Junior": "mark-boone-junior.jpg",
  "Mark Hamill": "mark-hamill.jpg",
  "Mark O'Brien": "mark-o-brien.jpg",
  "Mark Ruffalo": "mark-ruffalo.jpg",
  "Mark Rylance": "mark-rylance.jpg",
  "Mark Strong": "mark-strong.jpg",
  "Mark Wahlberg": "mark-wahlberg.jpg",
  "Marlee Matlin": "marlee-matlin.jpg",
  "Marlene Dietrich": "marlene-dietrich.jpg",
  "Marlon Brando": "marlon-brando.jpg",
  "Martha Scott": "martha-scott.jpg",
  "Martin Balsam": "martin-balsam.jpg",
  "Martin Freeman": "martin-freeman.jpg",
  "Martin Sheen": "martin-sheen.jpg",
  "Martina Gedeck": "martina-gedeck.jpg",
  "Marwan Kenzari": "marwan-kenzari.jpg",
  "Mary Elizabeth Mastrantonio": "mary-elizabeth-mastrantonio.jpg",
  "Mary McDonnell": "mary-mcdonnell.jpg",
  "Masayuki Mori": "masayuki-mori.jpg",
  "Mathieu Kassovitz": "mathieu-kassovitz.jpg",
  "Matt Damon": "matt-damon.jpg",
  "Matthew Broderick": "matthew-broderick.jpg",
  "Matthew Macfadyen": "matthew-macfadyen.jpg",
  "Matthew McConaughey": "matthew-mcconaughey.jpg",
  "Matthew Modine": "matthew-modine.jpg",
  "Maureen Lipman": "maureen-lipman.jpg",
  "Maya Hawke": "maya-hawke.jpg",
  "Meat Loaf": "meat-loaf.jpg",
  "Mel Gibson": "mel-gibson.jpg",
  "Melissa Benoist": "melissa-benoist.jpg",
  "Mena Massoud": "mena-massoud.jpg",
  "Mena Suvari": "mena-suvari.jpg",
  "Meryl Streep": "meryl-streep.jpg",
  "Mia Wasikowska": "mia-wasikowska.jpg",
  "Michael B. Jordan": "michael-b-jordan.jpg",
  "Michael Bates": "michael-bates.jpg",
  "Michael Caine": "michael-caine.jpg",
  "Michael Clarke Duncan": "michael-clarke-duncan.jpg",
  "Michael Fassbender": "michael-fassbender.jpg",
  "Michael Gambon": "michael-gambon.jpg",
  "Michael J. Fox": "michael-j-fox.jpg",
  "Michael Keaton": "michael-keaton.jpg",
  "Michael Madsen": "michael-madsen.jpg",
  "Michael Shannon": "michael-shannon.jpg",
  "Michael Stuhlbarg": "michael-stuhlbarg.jpg",
  "Michelle Pfeiffer": "michelle-pfeiffer.jpg",
  "Michelle Rodriguez": "michelle-rodriguez.jpg",
  "Michelle Williams": "michelle-williams.jpg",
  "Michelle Yeoh": "michelle-yeoh.jpg",
  "Mike Myers": "mike-myers.jpg",
  "Miles Teller": "miles-teller.jpg",
  "Millard Mitchell": "millard-mitchell.jpg",
  "Minoru Chiaki": "minoru-chiaki.jpg",
  "Miranda Cosgrove": "miranda-cosgrove.jpg",
  "Monica Bellucci": "monica-bellucci.jpg",
  "Morena Baccarin": "morena-baccarin.jpg",
  "Morgan Freeman": "morgan-freeman.jpg",
  "Murray Hamilton": "murray-hamilton.jpg",
  "Mykelti Williamson": "mykelti-williamson.jpg",
  "Mélanie Laurent": "melanie-laurent.jpg",
  "Nancy Olson": "nancy-olson.jpg",
  "Naomi Scott": "naomi-scott.jpg",
  "Naomi Watts": "naomi-watts.jpg",
  "Naomie Harris": "naomie-harris.jpg",
  "Natalie Portman": "natalie-portman.jpg",
  "Natascha McElhone": "natascha-mcelhone.jpg",
  "Nathan Lane": "nathan-lane.jpg",
  "Navid Negahban": "navid-negahban.jpg",
  "Ned Beatty": "ned-beatty.jpg",
  "Nicholas Colasanto": "nicholas-colasanto.jpg",
  "Nick Jonas": "nick-jonas.jpg",
  "Nicola Peltz": "nicola-peltz.jpg",
  "Nicole Kidman": "nicole-kidman.jpg",
  "Nicoletta Braschi": "nicoletta-braschi.jpg",
  "Noah Emmerich": "noah-emmerich.jpg",
  "Octavia Spencer": "octavia-spencer.jpg",
  "Oh Dal-su": "oh-dal-su.jpg",
  "Oliver Reed": "oliver-reed.jpg",
  "Olivia de Havilland": "olivia-de-havilland.jpg",
  "Omar Sharif": "omar-sharif.jpg",
  "Oona Chaplin": "oona-chaplin.jpg",
  "Orlando Bloom": "orlando-bloom.jpg",
  "Orson Welles": "orson-welles.jpg",
  "Oscar Isaac": "oscar-isaac.jpg",
  "Park So-dam": "park-so-dam.jpg",
  "Patrick Magee": "patrick-magee.jpg",
  "Patrick McGoohan": "patrick-mcgoohan.jpg",
  "Patrick Stewart": "patrick-stewart.jpg",
  "Patrick Wilson": "patrick-wilson.jpg",
  "Paul Dano": "paul-dano.jpg",
  "Paul Freeman": "paul-freeman.jpg",
  "Paul Henreid": "paul-henreid.jpg",
  "Paul Newman": "paul-newman.jpg",
  "Paul Reiser": "paul-reiser.jpg",
  "Paul Sorvino": "paul-sorvino.jpg",
  "Paul Walker": "paul-walker.jpg",
  "Paulette Goddard": "paulette-goddard.jpg",
  "Penélope Cruz": "penelope-cruz.jpg",
  "Perry Lopez": "perry-lopez.jpg",
  "Peter Boyle": "peter-boyle.jpg",
  "Peter Coyote": "peter-coyote.jpg",
  "Peter Cushing": "peter-cushing.jpg",
  "Peter Finch": "peter-finch.jpg",
  "Peter O'Toole": "peter-o-toole.jpg",
  "Philip Seymour Hoffman": "philip-seymour-hoffman.jpg",
  "Philippe Noiret": "philippe-noiret.jpg",
  "Phyllis Smith": "phyllis-smith.jpg",
  "Pierre Coffin": "pierre-coffin.jpg",
  "Porter Hall": "porter-hall.jpg",
  "Queen Latifah": "queen-latifah.jpg",
  "R. Lee Ermey": "r-lee-ermey.jpg",
  "Rachel McAdams": "rachel-mcadams.jpg",
  "Rafe Spall": "rafe-spall.jpg",
  "Ralph Fiennes": "ralph-fiennes.jpg",
  "Ralph Meeker": "ralph-meeker.jpg",
  "Rami Malek": "rami-malek.jpg",
  "Ray Liotta": "ray-liotta.jpg",
  "Ray Romano": "ray-romano.jpg",
  "Ray Walston": "ray-walston.jpg",
  "Raymond Burr": "raymond-burr.jpg",
  "Rebecca Ferguson": "rebecca-ferguson.jpg",
  "Reginald Gardiner": "reginald-gardiner.jpg",
  "Renée Victor": "renee-victor.jpg",
  "Richard Armitage": "richard-armitage.jpg",
  "Richard Attenborough": "richard-attenborough.jpg",
  "Richard Dreyfuss": "richard-dreyfuss.jpg",
  "Richard Harris": "richard-harris.jpg",
  "Richard Jenkins": "richard-jenkins.jpg",
  "Riz Ahmed": "riz-ahmed.jpg",
  "Robert De Niro": "robert-de-niro.jpg",
  "Robert Downey Jr.": "robert-downey-jr.jpg",
  "Robert Duvall": "robert-duvall.jpg",
  "Robert Loggia": "robert-loggia.jpg",
  "Robert MacNaughton": "robert-macnaughton.jpg",
  "Robert Patrick": "robert-patrick.jpg",
  "Robert Pattinson": "robert-pattinson.jpg",
  "Robert Redford": "robert-redford.jpg",
  "Robert Shaw": "robert-shaw.jpg",
  "Robert Stack": "robert-stack.jpg",
  "Roberto Benigni": "roberto-benigni.jpg",
  "Robin Wright": "robin-wright.jpg",
  "Ronald Lacey": "ronald-lacey.jpg",
  "Rooney Mara": "rooney-mara.jpg",
  "Rose Matafeo": "rose-matafeo.jpg",
  "Rosemarie DeWitt": "rosemarie-dewitt.jpg",
  "Rosie Huntington-Whiteley": "rosie-huntington-whiteley.jpg",
  "Rossella Falk": "rossella-falk.jpg",
  "Roy Dotrice": "roy-dotrice.jpg",
  "Roy Scheider": "roy-scheider.jpg",
  "Rufus": "rufus.jpg",
  "Rupert Friend": "rupert-friend.jpg",
  "Rupert Grint": "rupert-grint.jpg",
  "Russell Brand": "russell-brand.jpg",
  "Russell Crowe": "russell-crowe.jpg",
  "Rutger Hauer": "rutger-hauer.jpg",
  "Ryan Gosling": "ryan-gosling.jpg",
  "Ryan Reynolds": "ryan-reynolds.jpg",
  "Sally Field": "sally-field.jpg",
  "Sally Hawkins": "sally-hawkins.jpg",
  "Sam Neill": "sam-neill.jpg",
  "Sam Rockwell": "sam-rockwell.jpg",
  "Sam Worthington": "sam-worthington.jpg",
  "Samuel L. Jackson": "samuel-l-jackson.jpg",
  "Sandra Bullock": "sandra-bullock.jpg",
  "Sandra Milo": "sandra-milo.jpg",
  "Santino Fontana": "santino-fontana.jpg",
  "Saoirse Ronan": "saoirse-ronan.jpg",
  "Sarah Vowell": "sarah-vowell.jpg",
  "Saurabh Shukla": "saurabh-shukla.jpg",
  "Scarlett Johansson": "scarlett-johansson.jpg",
  "Scatman Crothers": "scatman-crothers.jpg",
  "Scott Glenn": "scott-glenn.jpg",
  "Sean Astin": "sean-astin.jpg",
  "Sean Young": "sean-young.jpg",
  "Sebastian Koch": "sebastian-koch.jpg",
  "Sebastian Maniscalco": "sebastian-maniscalco.jpg",
  "Sebastian Stan": "sebastian-stan.jpg",
  "Seiji Miyaguchi": "seiji-miyaguchi.jpg",
  "Sergi López": "sergi-lopez.jpg",
  "Sessue Hayakawa": "sessue-hayakawa.jpg",
  "Seth Rogen": "seth-rogen.jpg",
  "Shelley Duvall": "shelley-duvall.jpg",
  "Shia LaBeouf": "shia-labeouf.jpg",
  "Shirley MacLaine": "shirley-maclaine.jpg",
  "Sigourney Weaver": "sigourney-weaver.jpg",
  "Simon Pegg": "simon-pegg.jpg",
  "Simu Liu": "simu-liu.jpg",
  "Song Kang-ho": "song-kang-ho.jpg",
  "Sophie Marceau": "sophie-marceau.jpg",
  "Spencer Fox": "spencer-fox.jpg",
  "Stanley Tucci": "stanley-tucci.jpg",
  "Stellan Skarsgård": "stellan-skarsgard.jpg",
  "Stephanie Hsu": "stephanie-hsu.jpg",
  "Stephen Baldwin": "stephen-baldwin.jpg",
  "Stephen Boyd": "stephen-boyd.jpg",
  "Stephen Lang": "stephen-lang.jpg",
  "Stephen Merchant": "stephen-merchant.jpg",
  "Stephen Tobolowsky": "stephen-tobolowsky.jpg",
  "Sterling K. Brown": "sterling-k-brown.jpg",
  "Steve Buscemi": "steve-buscemi.jpg",
  "Steve Carell": "steve-carell.jpg",
  "Steve Coogan": "steve-coogan.jpg",
  "Steven Bauer": "steven-bauer.jpg",
  "Sydney Agudong": "sydney-agudong.jpg",
  "Takashi Shimura": "takashi-shimura.jpg",
  "Talia Shire": "talia-shire.jpg",
  "Taraji P. Henson": "taraji-p-henson.jpg",
  "Ted Levine": "ted-levine.jpg",
  "Tenoch Huerta": "tenoch-huerta.jpg",
  "Tessa Thompson": "tessa-thompson.jpg",
  "Thelma Ritter": "thelma-ritter.jpg",
  "Thomas F. Wilson": "thomas-f-wilson.jpg",
  "Thomas Haden Church": "thomas-haden-church.jpg",
  "Thomas Kretschmann": "thomas-kretschmann.jpg",
  "Thomas Mitchell": "thomas-mitchell.jpg",
  "Thomas Thieme": "thomas-thieme.jpg",
  "Thora Birch": "thora-birch.jpg",
  "Tim Allen": "tim-allen.jpg",
  "Tim Robbins": "tim-robbins.jpg",
  "Tim Roth": "tim-roth.jpg",
  "Timothée Chalamet": "timothee-chalamet.jpg",
  "Tiny Sandford": "tiny-sandford.jpg",
  "Tobey Maguire": "tobey-maguire.jpg",
  "Tom Berenger": "tom-berenger.jpg",
  "Tom Cruise": "tom-cruise.jpg",
  "Tom Hanks": "tom-hanks.jpg",
  "Tom Hardy": "tom-hardy.jpg",
  "Tom Helmore": "tom-helmore.jpg",
  "Tom Hiddleston": "tom-hiddleston.jpg",
  "Tom Holland": "tom-holland.jpg",
  "Tom Hulce": "tom-hulce.jpg",
  "Tom Sizemore": "tom-sizemore.jpg",
  "Tom Skerritt": "tom-skerritt.jpg",
  "Tommy Lee Jones": "tommy-lee-jones.jpg",
  "Tony Curtis": "tony-curtis.jpg",
  "Tony Hale": "tony-hale.jpg",
  "Tony Leung": "tony-leung.jpg",
  "Tony Revolori": "tony-revolori.jpg",
  "Tony Roberts": "tony-roberts.jpg",
  "Topher Grace": "topher-grace.jpg",
  "Toshirô Mifune": "toshiro-mifune.jpg",
  "Trevante Rhodes": "trevante-rhodes.jpg",
  "Trevor Howard": "trevor-howard.jpg",
  "Trey Parker": "trey-parker.jpg",
  "Troy Kotsur": "troy-kotsur.jpg",
  "Ty Burrell": "ty-burrell.jpg",
  "Tyrese Gibson": "tyrese-gibson.jpg",
  "Tyrone Power": "tyrone-power.jpg",
  "Ulrich Mühe": "ulrich-muhe.jpg",
  "Ulrich Tukur": "ulrich-tukur.jpg",
  "Uma Thurman": "uma-thurman.jpg",
  "Vera Miles": "vera-miles.jpg",
  "Viggo Mortensen": "viggo-mortensen.jpg",
  "Vin Diesel": "vin-diesel.jpg",
  "Vincent D'Onofrio": "vincent-d-onofrio.jpg",
  "Virginia Cherrill": "virginia-cherrill.jpg",
  "Vivien Leigh": "vivien-leigh.jpg",
  "Warren Clarke": "warren-clarke.jpg",
  "Wayne Morris": "wayne-morris.jpg",
  "Wendell Corey": "wendell-corey.jpg",
  "Wes Bentley": "wes-bentley.jpg",
  "Will Ferrell": "will-ferrell.jpg",
  "Will Poulter": "will-poulter.jpg",
  "Will Smith": "will-smith.jpg",
  "Willem Dafoe": "willem-dafoe.jpg",
  "William Holden": "william-holden.jpg",
  "William Sadler": "william-sadler.jpg",
  "William Sylvester": "william-sylvester.jpg",
  "Woody Allen": "woody-allen.jpg",
  "Woody Harrelson": "woody-harrelson.jpg",
  "Xochitl Gomez": "xochitl-gomez.jpg",
  "Yaphet Kotto": "yaphet-kotto.jpg",
  "Yoo Ji-tae": "yoo-ji-tae.jpg",
  "Yoshio Inaba": "yoshio-inaba.jpg",
  "Zach Galifianakis": "zach-galifianakis.jpg",
  "Zazie Beetz": "zazie-beetz.jpg",
  "Zendaya": "zendaya.jpg",
  "Zoe Saldana": "zoe-saldana.jpg",
};
