// composers por puesto de película y foto por persona
// Generado por tools/fetch-people.py --role composers
// Nombres: top_peliculas_taquilla_y_critica.xlsx · Fotos: Wikipedia en inglés
const COMPOSERS = {
  1: ["James Horner"],
  2: ["Alan Silvestri"],
  3: ["Simon Franglen"],
  4: ["James Horner"],
  5: ["John Williams"],
  6: ["Alan Silvestri"],
  7: ["Michael Giacchino"],
  8: ["Zhao Ying"],
  9: ["Michael Giacchino"],
  10: ["Michael Giacchino"],
  11: ["Andrea Datzman"],
  12: ["Michael Giacchino"],
  13: ["Hans Zimmer"],
  14: ["Alan Silvestri"],
  15: ["Brian Tyler"],
  16: ["Simon Franglen"],
  17: ["Hans Zimmer", "Lorne Balfe"],
  18: ["Christophe Beck"],
  19: ["Mark Ronson", "Andrew Wyatt"],
  20: ["Brian Tyler", "Danny Elfman"],
  21: ["Brian Tyler"],
  22: ["Hans Zimmer"],
  23: ["Rob Simonsen"],
  24: ["Ludwig Göransson"],
  25: ["John Williams"],
  26: ["Alexandre Desplat"],
  27: ["Michael Giacchino"],
  28: ["Christophe Beck"],
  29: ["Alan Menken"],
  30: ["Michael Giacchino"],
  31: ["Brian Tyler"],
  32: ["Brian Tyler"],
  33: ["Heitor Pereira"],
  34: ["Henry Jackman"],
  35: ["Rupert Gregson-Williams"],
  36: ["Michael Giacchino"],
  37: ["Pinar Toprak"],
  38: ["Howard Shore"],
  39: ["Steve Jablonsky"],
  40: ["Randy Newman"],
  41: ["Thomas Newman"],
  42: ["Steve Jablonsky"],
  43: ["Hans Zimmer"],
  44: ["Hildur Guðnadóttir"],
  45: ["Randy Newman"],
  46: ["John Williams"],
  47: ["Randy Newman"],
  48: ["Hans Zimmer"],
  49: ["Mark Mancina", "Opetaia Foa'i"],
  50: ["John Williams"],
  51: ["Michael Giacchino"],
  52: ["John Williams"],
  53: ["Hans Zimmer"],
  54: ["Alan Menken"],
  55: ["Alan Menken"],
  56: ["Heitor Pereira", "Pharrell Williams"],
  57: ["Danny Elfman"],
  58: ["Thomas Newman"],
  60: ["Michael Giacchino"],
  61: ["Howard Shore"],
  63: ["Hans Zimmer", "James Newton Howard"],
  64: ["Michael Giacchino"],
  65: ["Hans Zimmer"],
  66: ["Heitor Pereira"],
  67: ["Ludwig Göransson"],
  68: ["Heitor Pereira", "Pharrell Williams"],
  69: ["John Williams"],
  70: ["Henry Jackman"],
  71: ["Mark Mothersbaugh"],
  72: ["Hans Zimmer"],
  73: ["Howard Shore"],
  74: ["Danny Elfman"],
  75: ["John Debney"],
  76: ["Alexandre Desplat"],
  77: ["Howard Shore"],
  78: ["Heitor Pereira"],
  79: ["Nicholas Hooper"],
  80: ["Thomas Newman"],
  81: ["Harry Gregson-Williams"],
  82: ["Howard Shore"],
  83: ["Nicholas Hooper"],
  84: ["John Williams"],
  85: ["Howard Shore"],
  86: ["Christopher Young"],
  87: ["Patrick Doyle"],
  88: ["John Powell"],
  89: ["Alexandre Desplat"],
  90: ["John Powell"],
  91: ["John Ottman"],
  92: ["Thomas Newman"],
  93: ["Michael Giacchino"],
  94: ["John Williams"],
  95: ["Hans Zimmer", "Junkie XL"],
  96: ["Michael Giacchino"],
  97: ["Tyler Bates"],
  98: ["James Newton Howard"],
  99: ["Ludwig Göransson"],
  100: ["Ludwig Göransson"],
  101: ["Nino Rota"],
  102: ["Nino Rota", "Carmine Coppola"],
  103: ["Kenyon Hopkins"],
  104: ["John Williams"],
  106: ["Thomas Newman"],
  107: ["Miklós Rózsa"],
  108: ["Miklós Rózsa"],
  109: ["Charles Chaplin"],
  111: ["Nicola Piovani"],
  113: ["Miklós Rózsa"],
  115: ["Bernard Herrmann"],
  117: ["Antônio Pinto", "Ed Côrtes"],
  118: ["Ennio Morricone"],
  119: ["Max Steiner"],
  120: ["Fumio Hayasaka"],
  123: ["Franz Waxman"],
  124: ["Alan Silvestri"],
  125: ["John Williams"],
  126: ["Joe Hisaishi"],
  127: ["Ennio Morricone", "Andrea Morricone"],
  129: ["Miklós Rózsa"],
  130: ["Bernard Herrmann"],
  131: ["Bernard Herrmann"],
  133: ["Howard Shore"],
  134: ["Jung Jae-il"],
  136: ["Wojciech Kilar"],
  137: ["Jack Nitzsche"],
  138: ["The Dust Brothers"],
  140: ["Maurice Jarre"],
  141: ["Adolph Deutsch"],
  142: ["Ennio Morricone"],
  144: ["Hans Zimmer"],
  145: ["John Williams"],
  146: ["Brad Fiedel"],
  147: ["John Williams"],
  148: ["Thomas Newman"],
  149: ["Carmine Coppola", "Francis Ford Coppola"],
  150: ["Justin Hurwitz"],
  151: ["John Ottman"],
  152: ["Malcolm Arnold"],
  153: ["Don Davis"],
  154: ["Max Steiner"],
  155: ["John Williams"],
  156: ["Alan Silvestri"],
  157: ["Burkhard Dallwitz", "Philip Glass"],
  158: ["Jerry Goldsmith"],
  159: ["David Julyan"],
  160: ["Miklós Rózsa"],
  161: ["Jon Brion"],
  162: ["Bernard Herrmann"],
  163: ["Hans Zimmer"],
  164: ["Hans Zimmer", "Lisa Gerrard"],
  165: ["Thomas Newman"],
  166: ["Yann Tiersen"],
  167: ["Son Lux"],
  168: ["Éric Serra"],
  169: ["Wendy Carlos", "Rachel Elkind"],
  170: ["Vangelis"],
  171: ["Wendy Carlos"],
  172: ["Howard Shore"],
  173: ["Carter Burwell"],
  174: ["Giorgio Moroder"],
  175: ["John Williams"],
  176: ["John Williams"],
  179: ["James Horner"],
  180: ["Hans Zimmer"],
  181: ["Alexandre Desplat"],
  182: ["Jonny Greenwood"],
  183: ["Abigail Mead"],
  184: ["Trent Reznor", "Atticus Ross"],
  185: ["Nicholas Britell"],
  186: ["Justin Hurwitz"],
  187: ["Ludovico Einaudi"],
  188: ["Carmine Coppola", "Nino Rota"],
  189: ["Steven Price"],
  190: ["Alexandre Desplat"],
  191: ["Ryuichi Sakamoto", "Alva Noto"],
  192: ["Howard Shore"],
  193: ["Jerry Goldsmith"],
  194: ["Dimitri Tiomkin"],
  197: ["Miklós Rózsa"],
  198: ["Bernard Herrmann"],
  200: ["Stanley Myers"],
  201: ["Elliot Lawrence"],
  202: ["Lennie Niehaus"],
  203: ["Georges Delerue"],
  204: ["Javier Navarrete"],
  205: ["Gabriel Yared", "Stéphane Moucha"],
  206: ["Michael Galasso", "Shigeru Umebayashi"],
  209: ["David Julyan"],
  210: ["Jo Yeong-wook"],
  212: ["Howard Shore"],
  213: ["Antonio Sánchez"],
  214: ["Alexandre Desplat"],
  215: ["Alexandre Desplat"],
  216: ["A.R. Rahman"],
  217: ["Marius de Vries"],
  218: ["Kris Bowers"],
  219: ["Thomas Newman"],
  220: ["Michael Giacchino"],
  221: ["Rupert Gregson-Williams"],
  222: ["Danny Elfman"],
  223: ["David Arnold"],
  224: ["Tyler Bates"],
  225: ["Mark Mothersbaugh"],
  226: ["Michael Giacchino"],
  227: ["Michael Giacchino"],
  228: ["Hans Zimmer"],
  229: ["Hans Zimmer"],
  230: ["Marco Beltrami"],
  231: ["Thomas Newman"],
  233: ["Arcade Fire"],
  234: ["Jóhann Jóhannsson"],
  235: ["Hans Zimmer"],
};

const COMPOSER_PHOTOS = {
  "A.R. Rahman": "a-r-rahman.jpg",
  "Abigail Mead": "abigail-mead.jpg",
  "Alan Menken": "alan-menken.jpg",
  "Alan Silvestri": "alan-silvestri.jpg",
  "Alexandre Desplat": "alexandre-desplat.jpg",
  "Alfred Newman": "alfred-newman.jpg",
  "Andrea Morricone": "andrea-morricone.jpg",
  "Andrew Wyatt": "andrew-wyatt.jpg",
  "Anton Karas": "anton-karas.jpg",
  "Antonio Sánchez": "antonio-sanchez.jpg",
  "Antônio Pinto": "antonio-pinto.jpg",
  "Atticus Ross": "atticus-ross.jpg",
  "Bernard Herrmann": "bernard-herrmann.jpg",
  "Brad Fiedel": "brad-fiedel.jpg",
  "Brian Tyler": "brian-tyler.jpg",
  "Carmine Coppola": "carmine-coppola.jpg",
  "Charles Chaplin": "charles-chaplin.jpg",
  "Christophe Beck": "christophe-beck.jpg",
  "Christopher Young": "christopher-young.jpg",
  "Danny Elfman": "danny-elfman.jpg",
  "David Arnold": "david-arnold.jpg",
  "David Julyan": "david-julyan.jpg",
  "Dimitri Tiomkin": "dimitri-tiomkin.jpg",
  "Don Davis": "don-davis.jpg",
  "Ennio Morricone": "ennio-morricone.jpg",
  "Ernest Gold": "ernest-gold.jpg",
  "Francis Ford Coppola": "francis-ford-coppola.jpg",
  "Franz Waxman": "franz-waxman.jpg",
  "Fumio Hayasaka": "fumio-hayasaka.jpg",
  "Gabriel Yared": "gabriel-yared.jpg",
  "Georges Delerue": "georges-delerue.jpg",
  "Giorgio Moroder": "giorgio-moroder.jpg",
  "Hans Zimmer": "hans-zimmer.jpg",
  "Harry Gregson-Williams": "harry-gregson-williams.jpg",
  "Heitor Pereira": "heitor-pereira.jpg",
  "Hildur Guðnadóttir": "hildur-gunadottir.jpg",
  "Howard Shore": "howard-shore.jpg",
  "Jack Nitzsche": "jack-nitzsche.jpg",
  "James Horner": "james-horner.jpg",
  "James Newton Howard": "james-newton-howard.jpg",
  "Jean Constantin": "jean-constantin.jpg",
  "Jerry Goldsmith": "jerry-goldsmith.jpg",
  "Joe Hisaishi": "joe-hisaishi.jpg",
  "John Debney": "john-debney.jpg",
  "John Ottman": "john-ottman.jpg",
  "John Powell": "john-powell.jpg",
  "John Williams": "john-williams.jpg",
  "Jon Brion": "jon-brion.jpg",
  "Jonny Greenwood": "jonny-greenwood.jpg",
  "Jung Jae-il": "jung-jae-il.jpg",
  "Junkie XL": "junkie-xl.jpg",
  "Justin Hurwitz": "justin-hurwitz.jpg",
  "Jóhann Jóhannsson": "johann-johannsson.jpg",
  "Kris Bowers": "kris-bowers.jpg",
  "Lennie Niehaus": "lennie-niehaus.jpg",
  "Lisa Gerrard": "lisa-gerrard.jpg",
  "Lorne Balfe": "lorne-balfe.jpg",
  "Ludovico Einaudi": "ludovico-einaudi.jpg",
  "Ludwig Göransson": "ludwig-goransson.jpg",
  "Malcolm Arnold": "malcolm-arnold.jpg",
  "Marco Beltrami": "marco-beltrami.jpg",
  "Mark Mothersbaugh": "mark-mothersbaugh.jpg",
  "Mark Ronson": "mark-ronson.jpg",
  "Matty Malneck": "matty-malneck.jpg",
  "Maurice Jarre": "maurice-jarre.jpg",
  "Max Steiner": "max-steiner.jpg",
  "Meredith Willson": "meredith-willson.jpg",
  "Michael Giacchino": "michael-giacchino.jpg",
  "Miklós Rózsa": "miklos-rozsa.jpg",
  "Nicholas Britell": "nicholas-britell.jpg",
  "Nicola Piovani": "nicola-piovani.jpg",
  "Nino Rota": "nino-rota.jpg",
  "Opetaia Foa'i": "opetaia-foa-i.jpg",
  "Patrick Doyle": "patrick-doyle.jpg",
  "Pharrell Williams": "pharrell-williams.jpg",
  "Philip Glass": "philip-glass.jpg",
  "Randy Newman": "randy-newman.jpg",
  "Ryuichi Sakamoto": "ryuichi-sakamoto.jpg",
  "Shigeru Umebayashi": "shigeru-umebayashi.jpg",
  "Simon Franglen": "simon-franglen.jpg",
  "Son Lux": "son-lux.jpg",
  "Stanley Myers": "stanley-myers.jpg",
  "Steven Price": "steven-price.jpg",
  "Thomas Newman": "thomas-newman.jpg",
  "Trent Reznor": "trent-reznor.jpg",
  "Tyler Bates": "tyler-bates.jpg",
  "Vangelis": "vangelis.jpg",
  "Werner R. Heymann": "werner-r-heymann.jpg",
  "Wojciech Kilar": "wojciech-kilar.jpg",
  "Yann Tiersen": "yann-tiersen.jpg",
  "Éric Serra": "eric-serra.jpg",
};
